name: tests

on:
  push:
  pull_request:

jobs:
  linux_tests:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [7.3, 7.4]
        stability: [prefer-lowest, prefer-stable]

    name: PHP ${{ matrix.php }} - ${{ matrix.stability }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring
          tools: composer:v2
          coverage: none

      - name: Install dependencies
        run: composer update --${{ matrix.stability }} --prefer-dist --no-interaction --no-progress

      - name: Execute static analysis
        run: php vendor/bin/phpstan analyse

      - name: Execute tests
        run: php vendor/bin/pest --colors=always --verbose --group=unit
